# Generated by Django 4.0.4 on 2022-05-05 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoVotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('codigo', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='TipoVotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('codigo', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Votacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('idEstado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votaciones', to='app_votaciones.estadovotacion')),
                ('idFacultad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votaciones', to='app_votaciones.facultad')),
                ('idTipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votaciones', to='app_votaciones.tipovotacion')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='estudiantes', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('semestre', models.IntegerField()),
                ('idFacultad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes', to='app_votaciones.facultad')),
            ],
        ),
        migrations.CreateModel(
            name='Decano',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='decanos', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('idFacultad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decanos', to='app_votaciones.facultad')),
            ],
        ),
    ]
