# Generated by Django 4.0.4 on 2022-05-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_votaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votacion',
            name='semestre',
            field=models.IntegerField(),
        ),
    ]
