# Generated by Django 4.0.4 on 2022-04-22 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_votaciones', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
