# Generated by Django 4.0.4 on 2022-04-22 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_votaciones', '0005_auth_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='auth_user',
        ),
    ]
