# Generated by Django 4.0.4 on 2022-04-22 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_votaciones', '0007_alter_decano_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decano',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='decanos', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='estudiantes', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
