# Generated by Django 4.0.4 on 2022-04-22 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_votaciones', '0008_alter_decano_id_alter_estudiante_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoVotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('codigo', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='TipoVotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('codigo', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Votacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('codigo', models.CharField(max_length=45)),
                ('idEstado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votaciones', to='app_votaciones.estadovotacion')),
                ('idFacultad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votaciones', to='app_votaciones.facultad')),
                ('idTipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votaciones', to='app_votaciones.tipovotacion')),
            ],
        ),
    ]
